name: Build & Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          go build -ldflags="-X 'github.com/Alwin18/gcraft/cmd.Version=${VERSION}'" -o gcraft

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${VERSION}
          tag_name: ${VERSION}
          files: gcraft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
